language: rust
rust:
    - stable
    - beta
    - nightly

cache:
    cargo: ""
    directories:
        - fuzz/artifacts
        - fuzz/corpus/libfuzzer
        - fuzz/afl/outputs

install:
    - rustup component add rustfmt
    - rustup component add clippy

script:
    - tests/pre-commit.sh
    - set -x; if [ TRAVIS_RUST_VERSION = "nightly" ]; then tests/fuzz.sh || true; fi

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
    fast_finish: true
