language: rust
rust:
    - stable
    - beta
    - nightly

cache:
    cargo: ""

install:
    - rustup component add rustfmt
    - rustup component add clippy

script:
    - tests/pre-commit.sh
    - echo $TRAVIS_RUST_VERSION; if [ $TRAVIS_RUST_VERSION = "nightly" ]; then tests/fuzz.sh || true; fi

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
    fast_finish: true
