[package]
name = "rcc"
version = "0.2.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rcc/"
readme = "README.md"
categories = ["development-tools", "parser-implementations"]
license = "BSD-3-Clause"
keywords = ["C", "compiler", "recursive-descent", "cranelift"]

[dependencies]
lazy_static = "1"
ansi_term = "0.12"
cranelift = { git = "https://github.com/bytecodealliance/cranelift", version = "0.51" }
cranelift-module = { git = "https://github.com/bytecodealliance/cranelift", version = "0.51" }
cranelift-object = { git = "https://github.com/bytecodealliance/cranelift" }
env_logger = "0.7"
hexf = "0.1"
thiserror = ">=1.0.9"
log = "0.4"
target-lexicon = "0.9"
tempfile = "3"
pico-args = "0.3"
string-interner = "0.7"

[dev-dependencies]
walkdir = "2"

[profile.release]
lto = true

[profile.dev]
debug = false  # speeds up link time

[profile.test]
debug = false
