[package]
name = "compiler"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/rust-c-compiler/"
readme ="README.md"
categories = ["parser-implementations"]
license = "BSD-3-Clause"

[dependencies]
lazy_static = "1"
ansi_term = "0.11"
cranelift = "0.36"
cranelift-codegen = "0.36"
cranelift-entity = "0.36"
cranelift-faerie = "0.36"
cranelift-module = "0.36"
failure = "0.1"
target-lexicon = "0.4"

structopt = { version = "0.2", optional = true }

[profile.release]
lto = true

[features]
# it _is_ much nicer, but it also has about 50 dependencies
better_parsing = ["structopt"]
